name: docs
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install GDAL
              run: |
                  python -m pip install --upgrade pip
                  pip install --find-links=https://girder.github.io/large_image_wheels --no-cache GDAL

            - name: Install package and docs dependencies
              run: |
                  pip install -e .
                  pip install mkdocs mkdocs-material mkdocstrings mkdocstrings-python \
                      pymdown-extensions pygments mkdocs-jupyter \
                      mkdocs-git-revision-date-localized-plugin

            - run: mkdocs gh-deploy --force
